version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo "Building Angular project..."
      - ng build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/rx-route-auth/ s3://khfirstbucket --delete